# Generated by Django 3.0.3 on 2020-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='okay',
            field=models.CharField(default='True', max_length=200),
        ),
    ]
