# Generated by Django 3.0.3 on 2020-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200329_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='okay',
            field=models.BooleanField(default=True),
        ),
    ]
