# Generated by Django 3.0.3 on 2020-03-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200329_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='member',
        ),
    ]
